name: build

on:
  push:
    branches:
      - master
      - test-cicd
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  # release:
  #   types: [published]

  workflow_dispatch:

jobs:
  create-qvm:
    name: Create QVM
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        submodules: recursive

    - name: Build
      run: make BUILD_GAME_QVM=1 BUILD_GAME_SO=0 BUILD_BASEGAME=1 BUILD_MISSIONPACK=0

    - uses: actions/upload-artifact@v3.1.1
      with:
        name: vm
        path: build/release-linux-x86_64/oax/vm/
        if-no-files-found: error
        retention-days: 5

  create-testing:
    if: ${{ ( github.ref == 'refs/heads/master' ) }} && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [create-qvm]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3.0.1

      - name: Create pk3
        run: 7z a -tzip -r oa-brca-vm.pk3 ./vm/

      - name: Create brca directory
        run: mkdir ./brca

      - name: Move pk3
        run: mv oa-brca-vm.pk3 ./brca

      - name: Create package
        run: 7z a -tzip -r oa-brca-vm.zip ./brca/

      - name: Create latest build
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "pre-release"
          prerelease: true
          draft: true
          title: Latest Pre-release
          files: |
            *.zip

# update-release:
#   if: false || ${{ github.event_name == 'release' }}
#   needs: [create-qvm]
#   runs-on: ubuntu-latest

#   steps:
#     - name: Download Artifacts
#       uses: actions/download-artifact@v3.0.1

#     - name: Create pk3
#       run: 7z a -r oa-brca-vm.pk3 ./vm/

#     - name: Create brca directory
#       run: mkdir ./brca

#     - name: Move pk3
#       run: mv oa-brca-vm.pk3 ./brca

#     - name: Create package
#       run: 7z a -r oa-brca-vm.zip ./brca/

#     - name: Upload archive
#       uses: "svenstaro/upload-release-action@latest"
#       with:
#         repo_token: ${{ secrets.GITHUB_TOKEN }}
#         tag: ${{ github.ref }}
#         overwrite: true
#         file: oa-brca-vm.zip